In [3]:
import numpy as np
b = np.array([1,2,3])
print(b)

[1 2 3]


In [5]:
my_arr = np.array([[1,2,3],[4,5,6]])
print(my_arr)

[[1 2 3]
 [4 5 6]]


In [8]:
print(my_arr[1,2])#access a single element

6


In [10]:
print(my_arr[0,2])

3


In [11]:
print(my_arr.ndim)#rank

2


In [12]:
print(my_arr.shape)#n rows,m columns

(2, 3)


In [13]:
print(my_arr.size)#no of elements

6


In [14]:
print(type(my_arr))

<class 'numpy.ndarray'>


In [18]:
a = np.ones((3,2))#array of 1s
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
b = np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
c = np.random.random(3)
print(c)

[0.60259673 0.39132161 0.29232827]


In [21]:
d = np.full((2,2),12)
print(d)

[[12 12]
 [12 12]]


In [22]:
d = np.full((2,2), 12,dtype=np.float32)
print(d)

[[12. 12.]
 [12. 12.]]


In [27]:
x = np.arange(0,10,2)
print(x)
print(x.shape)
x.resize(2,5)
print(x.shape)

[0 2 4 6 8]
(5,)
(2, 5)


In [24]:
y = np.arange(6)
print(y)


[0 1 2 3 4 5]


In [25]:
z = np.linspace(0,10,6)
print(z)

[ 0.  2.  4.  6.  8. 10.]
